language: python
jobs:
  include:
    # Docker: checkstyle and unit tests (without coverage)
    - name: "Docker"
      services:
        - docker
      install:
        - make build-docker
      script:  # NOTE: needed to override the generic "script" section (no coverage)
        - make checkstyle-docker
        - make test-docker
      after_success:  # NOTE: needed to override the generic "after_success" section (no coveralls)
        - docker ps -a
    # Linux: checkstyle and unit tests (with coverage)
    - name: "Python 3.5 on Linux"
      python: 3.5
      install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.6 on Linux"
      python: 3.6
      install:
        - make build-linux
        - pip install coveralls
    - name: "Python 3.9 on Linux"
      python: 3.9
      install:
        - make build-linux
        - pip install coveralls
      script:  # NOTE: needed to override the generic "script" section (no checkstyle)
        - make test-coverage
    # MacOS: checkstyle and unit tests (with coverage)
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # macOS 10.14.6
      language: shell
      install:
        - make build-macos
        - pip3 install coveralls
    - name: "Python 3.8.5 on macOS"
      os: osx
      osx_image: xcode12  # macOS 10.15.7
      language: shell
      install:
        - make build-macos
        - pip3 install coveralls
script:
  - make checkstyle
  - make test-coverage
after_success:
  - coveralls