name: ninjadroid
base: core18
version: '4.5'
summary: Ninja Reverse Engineering on Android APK packages
description: |
  NinjaDroid is a simple tool to reverse engineering Android APK packages.

architectures:
  - build-on: amd64
    run-on: amd64

grade: stable
confinement: strict

parts:
  ninjadroid:
    plugin: python
    python-version: python3
    requirements:
      - "requirements/prod.txt"
    source: .
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - binutils
      - openjdk-11-jdk

apps:
  ninjadroid:
    command: usr/bin/python3 ninjadroid.py
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
